spring:
  redis:
    database: 0
    host: 192.168.1.200
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms
    password: 123456
  data:
    redis:
      repositories:
        enabled: false